import { NextRequest, NextResponse } from 'next/server';
import OpenAI from 'openai';
import { zodResponseFormat } from 'openai/helpers/zod';
import { z } from 'zod';

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

const ResearchBrief = z.object({
  title: z.string().describe('제안 연구 제목'),
  background: z.string().describe('연구 배경 (2-3문장)'),
  researchQuestions: z.array(z.string()).describe('연구 질문 2-3개'),
  methodology: z.string().describe('제안 방법론 (2-3문장)'),
  expectedContribution: z.string().describe('기대 기여 (1-2문장)'),
  riskScore: z.number().min(0).max(100).describe('리스크 점수 0-100'),
  noveltyScore: z.number().min(0).max(100).describe('새로움 점수 0-100'),
});

export async function POST(request: NextRequest) {
  try {
    const { papers, analyses, gaps, chatHistory } = await request.json();

    if (!papers || papers.length < 3) {
      return NextResponse.json(
        { error: 'At least 3 papers are required' },
        { status: 400 }
      );
    }

    // Build context
    let context = `선택된 논문 (${papers.length}개):\n`;
    papers.forEach((p: any, idx: number) => {
      const analysis = analyses?.[p.paperId];
      context += `${idx + 1}. ${p.title} (${p.year})\n`;
      if (analysis) {
        context += `   - 개요: ${analysis.overview}\n`;
        context += `   - 목표: ${analysis.goals}\n`;
      }
    });

    if (gaps && gaps.length > 0) {
      context += `\n식별된 Research Gaps:\n`;
      gaps.forEach((g: any, idx: number) => {
        context += `${idx + 1}. [${g.type}] ${g.hypothesis}\n`;
      });
    }

    if (chatHistory && chatHistory.length > 0) {
      context += `\n연구자와의 대화 내용:\n`;
      chatHistory.forEach((msg: any) => {
        context += `${msg.role === 'user' ? '연구자' : 'AI'}: ${msg.content.slice(0, 200)}...\n`;
      });
    }

    const completion = await openai.chat.completions.create({
      model: 'gpt-4o-mini',
      messages: [
        {
          role: 'system',
          content: `당신은 연구 제안서를 작성하는 전문가입니다.
주어진 논문, Gap, 대화 내용을 바탕으로 후속 연구 Brief를 작성합니다.
모든 응답은 한국어로 작성합니다.`,
        },
        {
          role: 'user',
          content: `다음 컨텍스트를 바탕으로 Research Brief를 작성해주세요:

${context}

요청사항:
1. 연구 제목 제안
2. 연구 배경 요약
3. 핵심 연구 질문 2-3개
4. 제안 방법론
5. 기대 기여
6. 리스크 점수 (0-100, 높을수록 실패 가능성 높음)
7. 새로움 점수 (0-100, 높을수록 새로운 연구)`,
        },
      ],
      response_format: zodResponseFormat(ResearchBrief, 'research_brief'),
    });

    const brief = JSON.parse(completion.choices[0].message.content || '{}');

    // Generate markdown
    const markdown = `# ${brief.title}

## Background
${brief.background}

## Research Questions
${brief.researchQuestions.map((q: string, i: number) => `${i + 1}. ${q}`).join('\n')}

## Methodology
${brief.methodology}

## Expected Contribution
${brief.expectedContribution}

---

**Risk Score:** ${brief.riskScore}/100 | **Novelty Score:** ${brief.noveltyScore}/100

---

*Generated by Moon Search Light*
*Based on ${papers.length} selected papers*
`;

    return NextResponse.json({ ...brief, markdown });
  } catch (error) {
    console.error('Error generating research brief:', error);
    return NextResponse.json(
      { error: 'Failed to generate research brief' },
      { status: 500 }
    );
  }
}
